site_name: Weekly Dev Chat
site_description: Every Tuesday at 12pm Mountain Time

site_url: https://weeklydevchat.com

theme:
    name: material
    palette:
        primary: teal
        accent: blue
    
    font:
        text: Roboto
    features:
    - navigation.indexes

    logo: assets/logo/png/square_logo_light_150.png
    favicon: assets/logo/Favicons/16X16_favicon2.png


# Enable the blogging behaviour (builtin plugin)
# see https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
plugins:
    - search
    - blog:
        blog_dir: .
        pagination_per_page: 3
        post_url_format: "{date}/{slug}"
        # more blog parameters here:
        # https://squidfunk.github.io/mkdocs-material/plugins/blog/


nav:
  - Home: index.md
  - Join: join.md
  - Hosts: hosts/index.md
  - Past Hosts: past-hosts/index.md
  - Sponsors: sponsors/index.md

exclude_docs: |
    past_topics.md
markdown_extensions:
  - attr_list  # This lets us specify image dimensions, etc.

extra_css: 
  - stylesheets/extra.css
